---
- name: Imports a PowerShell module on the remote host
  hosts: all
  gather_facts: true
  vars:
    source: files/ShowCalendar.psm1
    destination: 'C:\Program Files\WindowsPowerShell\Modules\ShowCalendar.psm1'
    module: Show-Calendar
  
  tasks:
  - name: Copy module to host
    win_copy: 
      force: yes
      src: "{{ source }}"
      dest: "{{ destination }}"
  
  - name: Import module
    win_shell: "Import-Module {{ destination }}; {{ module }}" 
    register: result
    
  - debug:
      var: result.stdout
