---
- name: Imports a PowerShell module on the remote host
  hosts: all
  gather_facts: true
  vars:
    destination: 'C:\tmp'
  
  tasks:
  - name: Copy module to host
    win_copy: 
      force: yes
      src: files/ShowCalendar.psm1
      dest: "{{ destination }}/ShowCalendar.psm1"
  
  - name: Import module
    win_shell: Import-Module "{{ destination }}/ShowCalendar.psm1"
    
  - name: Test module
    win_shell: Show-Calendar
    register: cal
    
  - debug:
      var: cal
