---
# This playbook tests the script module on Windows hosts

- name: Run powershell script
  hosts: all 
  gather_facts: true
  
  tasks:
    - name: Run powershell script
      script: files/helloworld.ps1
      register: output
    
    - name: Show Version
      debug:
        var: output.stdout_lines
