---
- name: Update Windows
  hosts: all 
  gather_facts: true
  
  tasks:
  - name: Windows Update
    win_updates:
      log_path: c:\ansible_updates.txt
      category_names:
        - SecurityUpdates
        - CriticalUpdates
