---
- name: Delete a VM
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    resource_group: group
    vm_name: name
    storage_account_name: storage
    virtual_network_name: network
    client: clientid
    secret: clientsecret
    sub: subid
    tenant: tenant
    publisher: RedHat
    offer: rhel_byol
    version: Latest
    sku: 7.3

  tasks:
  - name: Remove VM and all resources
    azure_rm_virtualmachine:
      client_id: "{{ client }}"
      secret: "{{ secret }}"
      subscription_id: "{{ sub }}"
      tenant: "{{ tenant }}"
      resource_group: "{{ resource_group }}"    
      name: "{{ vm_name }}"
      state: absent
      remove_on_absent: all
