---
- name: List available offers
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    sub: mysub
  
  tasks:
  - name: Image facts
    azure_rm_virtualmachineimage_facts:
      location: eastus
      subscription_id: "{{ sub }}"
