---
- name: List available offers
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    client: clientid
    secret: clientsecret
    sub: subid
    tenant: tenant
    publisher: Red Hat
    version: 7.3
  
  tasks:
  - name: Image facts
    azure_rm_virtualmachineimage_facts:
      location: eastus
      client_id: "{{ client }}"
      secret: "{{ secret }}"
      subscription_id: "{{ sub }}"
      tenant: "{{ tenant }}"
      publisher: "{{ publisher }}"
      version: "{{ version }}"
