---
- name: List available offers
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    client: clientid
    secret: clientsecret
    sub: subid
    tenant: tenant
    name: name
  
  tasks:
  - name: Image facts
    azure_rm_virtualmachineimage_facts:
      location: eastus
      name: "{{ name }}"
      client_id: "{{ client }}"
      secret: "{{ secret }}"
      subscription_id: "{{ sub }}"
      tenant: "{{ tenant }}"
