---
- name: List available offers
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    image: img
  
  tasks:
  - name: Image facts
    azure_rm_virtualmachineimage_facts:
      location: eastus
      image: "{{ image }}"
