---
- name: Add a host to IDM
  hosts: all
  vars:
    idm_host: idm_host
    idm_passwd: idm_pass
    idm_zone: idm_zone
    idm_value: dns_record
    idm_record: 24
    
  tasks:
  - name: Add the host first
    ipa_host:
      fqdn: "{{ idm_record }}"
      state: present
      ipa_host: "{{ idm_host }}"
      ipa_user: admin
      ipa_pass: "{{ idm_pass }}"

  - name: Ensure a DNS record is present
    ipa_dnsrecord:
      ipa_host: "{{ idm_host }}"
      ipa_pass: "{{ idm_pass }}"
      state: present
      zone_name: "{{ idm_zone }}"
      record_name: "{{ idm_record }}"
      record_type: 'A'
      record_value: "{{ idm_value }}"
