---
- name: Add a host to IDM
  hosts: all
  vars:
    idm_server: idm_host
    idm_passwd: idm_pass
    idm_zone: idm_zone
    idm_record: fqdn
    idm_value: ipaddress
    idm_hostname: shorthostname

    
  tasks:
  - name: Ensure a DNS record is present
    ipa_dnsrecord:
      ipa_host: "{{ idm_server }}"
      ipa_pass: "{{ idm_pass }}"
      state: present
      zone_name: "{{ idm_zone }}"
      record_name: "{{ idm_record }}"
      record_type: 'A'
      record_value: "{{ idm_value }}"  
  
  - name: Add the host
    ipa_host:
      ocp.cloudsalab.com
      name: "{{ idm_hostname }}"
      state: present
      ipa_host: "{{ idm_server }}"
      ipa_user: admin
      ipa_pass: "{{ idm_pass }}"
      
  - name: Ping the newly added host
    ping: "{{ idm_record }}"

   
