---
- name: Sets the hostname 
  hosts: all
  remote_user: root
  vars: 
    hostname: fqdn
  
  tasks:
  - name: Applies the hostname to a single host in the self group
    hostname:
      name: "{{hostname}}"
...
