---
- name: Terminate instance in AWS EC2
  hosts: localhost
  gather_facts: False
  vars:
    access_key: accesskey
    secret_key: secretkey
    instance_id: instance
    
  tasks:
  - name: Provision
    ec2:
      state: 'absent'
      instance_ids: "{{ instance_id }}"
