---
- name: Provision instance in AWS EC2
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    access_key: accesskey
    secret_key: secretkey
    flavor: t2.micro
    count: 1
    subnet: subnet
    
  tasks:
  - name: Provision
    ec2:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      instance_type: "{{ flavor }}"
      image: ami-0ea6af64
      key_name: OpenShift
      wait: yes
      count: "{{ count }}"
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: no
      region: us-east-1
