---
- name: wait for sshd  
  wait_for:
    port: 22
    delay: 5
    
- name: register with red hat network
  shell: 
    subscription-manager register --username={{ rhn_user }} --password={{ rhn_pass }} --force &&
    subscription-manager attach --pool={{ rhn_pool }}
  ignore_errors: yes
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  
- name: let subscription manager settle
  pause:
    seconds: 30
