---
- name: Delete DNS record 
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: absent
    zone_name: "{{ domain }}"
    record_name: "{{ inventory_hostname }}"
    validate_certs: False

- name: Delete DNS record for apps subdomain
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: absent
    zone_name: "{{ domain }}"
    record_name: "*.apps"
    validate_certs: False
  when: inventory_hostname == groups['masters'][0]

- name: Delete the host
  ipa_host:
    name: "{{ inventory_hostname }}.{{ domain }}"
    state: absent
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    validate_certs: False
