---  
- name: Delete DNS record 
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: absent
    zone_name: "{{ domain }}"
    record_name: "{{ inventory_hostname }}"
    record_value: "{{ lookup('dig', fqdn)}}"
    validate_certs: False
  delegate_to: tower
  register: dnsrecord

- debug:
    var: dnsrecord

- name: Delete DNS record for apps subdomain
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: absent
    zone_name: "{{ domain }}"
    record_name: "*.apps"
    record_value: "{{ dnsrecord.ip }}"
    validate_certs: False
  when: inventory_hostname == groups['masters'][0]
  delegate_to: tower

- name: Delete the host
  ipa_host:
    name: "{{ fqdn }}"
    state: absent
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    validate_certs: False
  delegate_to: tower
