---
- name: subscription registration
  hosts: all
  gather_facts: no
  vars:
    username: user
    passwd: passwd
    pool: pool
  tasks:
    - name: wait for sshd  
      wait_for:
        port: 22
        delay: 5
    - name: register with red hat network
      shell: 
        subscription-manager register --username={{ username }} --password={{ passwd }} --force &&
        subscription-manager attach --pool={{ pool }}
      ignore_errors: yes
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0
      async: 180
      poll: 0
      register: registration

    - name: check on registration
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job
      until: job.finished
      retries: 30
      with_items: "{{ registration.results }}"
      
    - name: let subscription manager settle
      pause:
        seconds: 30
