---
- name: subscription registration
  hosts: all
  gather_facts: no
  vars:
    username: user
    passwd: passwd
    pool: pool
  tasks:
    - name: wait for sshd  
      wait_for:
        port: 22
        delay: 5
    - name: register with red hat network
      shell: 
        subscription-manager register --username={{ username }} --password={{ passwd }} --force &&
        subscription-manager attach --pool={{ pool }}
      ignore_errors: yes  
    - name: let subscription manager settle
      pause:
        seconds: 15
