---
- name: subscription registration
  hosts: all
  gather_facts: no
  vars:
    username: user
    passwd: passwd
    pool: pool
  tasks:
    - name: wait for sshd  
      wait_for:
        port: 22
        delay: 5
    - name: register with red hat network
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ passwd }}"
        pool: "{{ pool }}"
    - name: let subscription manager settle
      pause:
        seconds: 30
