---
- name: Install necessary packages
  yum:  
    name: '{{ item }}'
    state: present
  with_items: 
  - wget 
  - git 
  - net-tools 
  - bind-utils 
  - iptables-services 
  - bridge-utils 
  - bash-completion 
  - kexec-tools 
  - sos 
  - psacct
  - atomic-openshift-utils
  - docker-1.12.6
  - ipa-client
  - httpd-tools

- name: Update the system
  yum:  
    name: '*'

- name: restart server  
  shell: sleep 2 && /sbin/shutdown -r now "RedHat system package upgraded"
  async: 1
  poll: 0

- name: waiting 60 secs for server to come back
  become: false
  local_action: wait_for 
    host: "{{ ansible_default_ipv4.address }}" 
    port: 22 
    state: started 
    delay: 60 
    timeout: 120