---
- name: install httpd and start the service
  hosts: all
  remote_user: cloud-user
  become: yes
  
  tasks:      
  - name: install httpd
    yum:
      name: httpd
      state: latest
    ignore_errors: yes
    retries: 3
    delay: 5      
    register: result
    until: result.rc == 0
      
  - name: start httpd service
    service:
      name: httpd
      state: started

