---
- name: Installs httpd and starts the service
  hosts: all
  remote_user: cloud-user
  become: yes
  
  tasks:
  - name: Let subscription manager catch-up
    pause:
      seconds: 10
      
  - name: Install httpd
    yum:
      name: httpd
      state: latest
  - name: Starts httpd service
    service:
      name: httpd
      state: started
