---
- name: Ensure a DNS record is present
  ipa_dnsrecord:
    ipa_host: "{{ idm_server }}"
    ipa_pass: "{{ idm_pass }}"
    state: present
    zone_name: "{{ idm_zone }}"
    record_name: "{{ inventory_hostname }}"
    record_type: "A"
    record_value: "{{ ansible_default_ipv4.address }}"
  delegate_to: "{{ idm_server }}"

- name: Add the host
  ipa_host:
    name: "{{ inventory_hostname }}.{{ idm_zone }}"
    state: present
    ipa_host: "{{ idm_server }}"
    ipa_user: admin
    ipa_pass: "{{ idm_pass }}"
  delegate_to: "{{ idm_server }}"

- name: Copy dhclient.conf
  become: True
  template:
    src: dhclient.conf.j2
    dest: /etc/dhclient.conf

- name: Set resolv.conf
  become: True
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf    

- name: Restart network service
  become: True
  service:
    name: network
    state: restarted      
