---
- name: create ssh key
  shell: echo -e  'y\n' | ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  when: inventory_hostname == groups['masters'][0]

- name: capture master public key during cluster install
  shell: "cat ~/.ssh/id_rsa.pub"  
  register: pubkey
  when: inventory_hostname == groups['masters'][0]

- name: capture master public key during cluster expansion
  shell: "cat ~/.ssh/id_rsa.pub"  
  register: pubkey
  when: inventory_hostname in groups['new_nodes']  
  run_once: true
  delegate_to: "{{ hostvars[inventory_hostname]['ocp-master'] }}" 

- name: set the pubkey fact on the master
  set_fact:
    masterpubkey: "{{ pubkey.stdout }}"
  when: inventory_hostname == groups['masters'][0]

- name: add key to authorized keys
  authorized_key: 
    user: "{{ ansible_user }}"
    state: present
    key: "{{ hostvars[groups['masters'][0]]['masterpubkey'] }}"  
  
   
