---
- name: wait for sshd  
  wait_for:
    port: 22
    delay: 5
    
- name: register with red hat network
  become: True
  shell: 
    subscription-manager register --username={{ username }} --password={{ password }} --force &&
    subscription-manager attach --pool={{ pool }}
  ignore_errors: yes
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0

- name: Disable all repos
  become: True
  command: subscription-manager repos --disable "*"

- name: Enable necessary repos
  become: True
  command: subscription-manager repos --enable="rhel-7-server-rpms"     --enable="rhel-7-server-extras-rpms"     --enable="rhel-7-server-ose-{{ version }}-rpms"     --enable="rhel-7-fast-datapath-rpms"
  