---
- name: infoblox next available ip
  debug:
    var: "{{ infoblox_ip }}"

- name: launch an instance
  os_server:
    state: present
    auth:
      auth_url: "{{ osp_server }}"
      username: "{{ osp_user }}"
      password: "{{ osp_pass }}"
      project_name: "{{ osp_tenant }}"
    name: "{{ osp_instance_name }}"
    image: "{{ osp_image }}"
    key_name: "{{ osp_key }}"
    timeout: 200
    flavor: "{{ osp_flavor }}"
    security_groups: "{{ osp_security_group }}"
    network: "{{ osp_network }}"
    auto_ip: "{{ osp_floating_ip }}"
    wait: true
    userdata: |
      #cloud-config
      ssh_authorized_keys:
        - "{{ osp_public_key }}"
  register: instance
  delegate_to: "{{ control_machine }}"

- name: attach the IP to the instance
  os_floating_ip:    
    auth:
      auth_url: "{{ osp_server }}"
      username: "{{ osp_user }}"
      password: "{{ osp_pass }}"
      project_name: "{{ osp_tenant }}"
    state: present
    server: "{{ osp_instance_name }}"
    floating_ip_address: "{{ infoblox_ip }}"
    wait: true

- name: add the public IP address as a fact
  set_fact:
    ansible_default_ipv4:
      address: "{{ infoblox_ip }}"
    cacheable: True

- debug:
    msg: IP address is {{ ansible_default_ipv4.address }}

# - name: create volumes
#   os_volume:
#     auth:
#       auth_url: "{{ osp_server }}"
#       username: "{{ osp_user }}"
#       password: "{{ osp_pass }}"
#       project_name: "{{ osp_tenant }}"
#     state: present
#     size: "{{ osp_volume_size }}"
#     display_name: "{{ osp_instance_name }}-{{ osp_volume_name }}"
#   delegate_to: "{{ control_machine }}"

# - name: attach volumes  
#   os_server_volume:
#     auth:
#       auth_url: "{{ osp_server }}"
#       username: "{{ osp_user }}"
#       password: "{{ osp_pass }}"
#       project_name: "{{ osp_tenant }}"
#     state: present    
#     server: "{{ osp_instance_name }}"
#     volume: "{{ osp_instance_name }}-{{ osp_volume_name }}"
#   delegate_to: "{{ control_machine }}"