---
- name: Enforces a given number of application instances in OpenStack to exist
  hosts: localhost
  gather_facts: false
  vars:
    prefix: cfme-w
    min: 3
    max: 5
    state: running
  
  tasks:
  - name: Get instances that start with {{ prefix }}
    os_server_facts:
      auth:
        auth_url: "{{ osp_server }}"
        username: "{{ osp_user }}"
        password: "{{ osp_pass }}"
        project_name: "{{ osp_tenant }}"
      server: "{{ prefix }}*"
      
  - debug:
      var: openstack_servers    
