---
- name: Destroys instances
  hosts: localhost
  vars:
    instances:
  tasks:
  - name: Delete OSP instance
    os_server:
      state: absent
      auth:
        auth_url: "{{ openstack }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project_name: "{{ tenant }}"
      name: "{{ item }}"
    with_items: "{{ instances }}"
