---
- name: Create an OpenStack instance
  hosts: localhost
  gather_facts: False
  remote_user: cloud-user
  vars:
    control_machine: cfme-w4
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  roles:
    - { role: provision }