- name: Create OpenShift project
  hosts: all
  vars:
    project: name
    token: ocptoken
  
  tasks:  
  - name: Create project
    oc:
      state: present
      inline:
        kind: ProjectRequest
        metadata:
          name: "{{ project }}"
        description: This project was created using Ansible
      token: "{{ token }}"
