- name: Create OpenShift project
  hosts: localhost
  connection: local
  vars:
    project: name
    token: ocptoken
    host: ocpapi
  
  tasks:  
  - name: Create project
    oc:
      state: present
      host: "{{ host }}"
      validate_certs: False
      inline:
        kind: ProjectRequest
        metadata:
          name: "{{ project }}"
        description: This project was created using Ansible
      token: "{{ token }}"
