---
- name: Create parksmap instance in OpenShift
  hosts: all
  user: ec2-user
  gather_facts: no
  
  tasks:
  - name: Invoke shell script
    command: /home/ec2-user/scripts/dockerimage.sh

- name: get parksmap url
  hosts: all
  user: ec2-user
  gather_facts: no
  
  tasks:
  - name: tail file
    command: tail -1 /home/ec2-user/parksmap
    register: url

  - name: show url
    debug:
      var: url.stdout
...
