---
- name: Create parksmap instance in OpenShift
  hosts: localhost
  connection: local
  user: cloud-user
  gather_facts: no
  tasks:
    - name: invoke remote shell script
      raw: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ec2-user@ocp.lamotta.co /home/ec2-user/scripts/dockerimage.sh
...
