---
- name: Create SSH keys on the master and copy to all nodes in the cluster
  hosts: all
  tasks:

  - name: create ssh key on cloud-user account
    shell: 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""'
    when: ansible_hostname == "ocp"

  - name: capture master public key
    shell: "cat ~/.ssh/id_rsa.pub"  
    register: pubkey
    when: ansible_hostname == "ocp"

  - debug:
      var:
        pubkey

  - name: add key to authorized keys
    authorized_key: 
      user: cloud-user
      state: present
      key: "{{ pubkey }}"
