---
- name: Keep alive ServiceNow Developer Instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    snow_host: hostname
    snow_user: username
    snow_pass: password
    
  tasks:
  - name: Login to SNOW
    uri:
      url: "{{ snow_host }}"
      method: POST
      user: "{{ snow_user }}"
      password: "{{ snow_pass }}"
...
